#!/usr/bin/env bash
# Ставит Docker (если нужно) и поднимает SearXNG по актуальной схеме upstream.
# https://docs.searxng.org/admin/installation-docker.html
set -euo pipefail

APP_DIR="${XELITY_DIR:-/opt/xelity}"
SEARX_DIR="${APP_DIR}/deploy/searxng"
COMPOSE_FILE="${SEARX_DIR}/docker-compose.yml"
CONFIG_DIR="${SEARX_DIR}/core-config"
SETTINGS="${CONFIG_DIR}/settings.yml"
LEGACY_SETTINGS="${SEARX_DIR}/settings.yml"
SEARX_ENV="${SEARX_DIR}/.env"
APP_ENV="${APP_DIR}/.env"
SEARX_URL="${SEARXNG_URL:-http://127.0.0.1:8888}"

if [[ "${EUID}" -ne 0 ]]; then
  echo "Запусти от root: sudo bash deploy/ensure-searxng.sh"
  exit 1
fi

if [[ ! -f "${COMPOSE_FILE}" ]]; then
  echo "Нет ${COMPOSE_FILE} — пропуск SearXNG"
  exit 0
fi

ensure_docker() {
  if command -v docker >/dev/null 2>&1; then
    return 0
  fi
  echo ">> Устанавливаю Docker…"
  apt-get update -y
  apt-get install -y ca-certificates curl gnupg
  install -m 0755 -d /etc/apt/keyrings
  if [[ ! -f /etc/apt/keyrings/docker.asc ]]; then
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    chmod a+r /etc/apt/keyrings/docker.asc
  fi
  . /etc/os-release
  echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu ${VERSION_CODENAME} stable" \
    > /etc/apt/sources.list.d/docker.list
  apt-get update -y
  apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
  systemctl enable --now docker
}

migrate_legacy_settings() {
  mkdir -p "${CONFIG_DIR}"
  if [[ ! -f "${SETTINGS}" && -f "${LEGACY_SETTINGS}" ]]; then
    echo ">> миграция settings.yml → core-config/"
    mv "${LEGACY_SETTINGS}" "${SETTINGS}"
  fi
  if [[ ! -f "${SETTINGS}" ]]; then
    echo "Нет ${SETTINGS}"
    return 1
  fi
}

ensure_searx_env() {
  local secret
  if [[ -f "${SEARX_ENV}" ]] && grep -qE '^SEARXNG_SECRET=.' "${SEARX_ENV}" 2>/dev/null; then
    secret="$(grep -E '^SEARXNG_SECRET=' "${SEARX_ENV}" | head -1 | cut -d= -f2-)"
  else
    secret="$(openssl rand -hex 32)"
  fi

  umask 077
  cat > "${SEARX_ENV}" <<EOF
# generated by ensure-searxng.sh — https://docs.searxng.org/admin/installation-docker.html
SEARXNG_VERSION=latest
SEARXNG_SECRET=${secret}
SEARXNG_BASE_URL=${SEARX_URL}/
SEARXNG_LIMITER=false
SEARXNG_PUBLIC_INSTANCE=false
FORCE_OWNERSHIP=true
EOF
  chmod 600 "${SEARX_ENV}"

  # убрать плейсхолдер из settings.yml, если остался
  if grep -qE 'xelity-change-me-on-install|ultrasecretkey' "${SETTINGS}" 2>/dev/null; then
    sed -i "s/xelity-change-me-on-install/${secret}/; s/ultrasecretkey/${secret}/" "${SETTINGS}"
  fi
}

ensure_app_env() {
  touch "${APP_ENV}"
  if grep -qE '^SEARXNG_URL=' "${APP_ENV}" 2>/dev/null; then
    sed -i "s|^SEARXNG_URL=.*|SEARXNG_URL=${SEARX_URL}|" "${APP_ENV}"
  else
    printf '\nSEARXNG_URL=%s\n' "${SEARX_URL}" >> "${APP_ENV}"
    touch /var/lock/xelity-restart-after-searxng
    echo ">> В .env добавлен SEARXNG_URL — нужен рестарт xelity"
  fi
}

compose() {
  if docker compose version >/dev/null 2>&1; then
    docker compose -f "${COMPOSE_FILE}" --project-directory "${SEARX_DIR}" "$@"
  else
    docker-compose -f "${COMPOSE_FILE}" "$@"
  fi
}

ensure_docker
migrate_legacy_settings
ensure_searx_env
ensure_app_env

# права: контейнер searxng (uid внутри образа) + FORCE_OWNERSHIP
chmod -R a+rX "${CONFIG_DIR}" || true

echo ">> SearXNG: docker compose up -d"
cd "${SEARX_DIR}"
compose pull || true
compose up -d --remove-orphans --force-recreate

# healthcheck + тест JSON API
# https://docs.searxng.org/dev/search_api.html
for i in $(seq 1 20); do
  if curl -fsS "${SEARX_URL}/" >/dev/null 2>&1; then
    if curl -fsS "${SEARX_URL}/search?q=xelity&format=json" \
      -H 'Accept: application/json' 2>/dev/null | grep -q '"results"'; then
      echo ">> SearXNG готов (JSON): ${SEARX_URL}"
      exit 0
    fi
    echo ">> SearXNG отвечает, ждём JSON… (${i})"
  else
    echo ">> ждём SearXNG… (${i})"
  fi
  sleep 2
done

echo "!! SearXNG ещё не отдаёт JSON. Логи:"
compose ps || true
compose logs --tail=60 || true
echo "Поиск всё равно работает через DuckDuckGo/Wikipedia fallback в API."
exit 0
