#!/usr/bin/env bash
# Ставит Docker (если нужно) и поднимает SearXNG.
# По умолчанию быстрый путь: если контейнер уже здоров — ничего не тянем.
#   bash ensure-searxng.sh           # quick
#   bash ensure-searxng.sh --force   # pull + recreate
#   SEARXNG_FORCE=1 bash ensure-searxng.sh
set -euo pipefail

APP_DIR="${XELITY_DIR:-/opt/xelity}"
SEARX_DIR="${APP_DIR}/deploy/searxng"
COMPOSE_FILE="${SEARX_DIR}/docker-compose.yml"
CONFIG_DIR="${SEARX_DIR}/core-config"
SETTINGS="${CONFIG_DIR}/settings.yml"
LEGACY_SETTINGS="${SEARX_DIR}/settings.yml"
SEARX_ENV="${SEARX_DIR}/.env"
APP_ENV="${APP_DIR}/.env"
SEARX_URL="${SEARXNG_URL:-http://127.0.0.1:8888}"

FORCE=0
for arg in "$@"; do
  case "${arg}" in
    --force|-f) FORCE=1 ;;
  esac
done
if [[ "${SEARXNG_FORCE:-0}" == "1" ]]; then
  FORCE=1
fi

if [[ "${EUID}" -ne 0 ]]; then
  echo "Запусти от root: sudo bash deploy/ensure-searxng.sh"
  exit 1
fi

if [[ ! -f "${COMPOSE_FILE}" ]]; then
  echo "Нет ${COMPOSE_FILE} — пропуск SearXNG"
  exit 0
fi

compose() {
  if docker compose version >/dev/null 2>&1; then
    docker compose -f "${COMPOSE_FILE}" --project-directory "${SEARX_DIR}" "$@"
  else
    docker-compose -f "${COMPOSE_FILE}" "$@"
  fi
}

searx_healthy() {
  curl -fsS --connect-timeout 1 --max-time 2 "${SEARX_URL}/" >/dev/null 2>&1 \
    && curl -fsS --connect-timeout 1 --max-time 3 \
      "${SEARX_URL}/search?q=xelity&format=json" \
      -H 'Accept: application/json' 2>/dev/null | grep -q '"results"'
}

# ——— быстрый выход, если уже работает ———
if [[ "${FORCE}" -eq 0 ]] && command -v docker >/dev/null 2>&1; then
  if searx_healthy; then
    echo ">> SearXNG уже работает — пропуск (для обновления образа: --force)"
    exit 0
  fi
  # контейнер есть, но ещё стартует — up без pull
  if docker ps --format '{{.Names}}' 2>/dev/null | grep -qiE 'searx'; then
    echo ">> SearXNG контейнер есть, ждём health…"
    for i in $(seq 1 8); do
      if searx_healthy; then
        echo ">> SearXNG готов: ${SEARX_URL}"
        exit 0
      fi
      sleep 1
    done
  fi
fi

ensure_docker() {
  if command -v docker >/dev/null 2>&1; then
    return 0
  fi
  echo ">> Устанавливаю Docker…"
  apt-get update -y
  apt-get install -y ca-certificates curl gnupg
  install -m 0755 -d /etc/apt/keyrings
  if [[ ! -f /etc/apt/keyrings/docker.asc ]]; then
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    chmod a+r /etc/apt/keyrings/docker.asc
  fi
  . /etc/os-release
  echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu ${VERSION_CODENAME} stable" \
    > /etc/apt/sources.list.d/docker.list
  apt-get update -y
  apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
  systemctl enable --now docker
}

migrate_legacy_settings() {
  mkdir -p "${CONFIG_DIR}"
  if [[ ! -f "${SETTINGS}" && -f "${LEGACY_SETTINGS}" ]]; then
    echo ">> миграция settings.yml → core-config/"
    mv "${LEGACY_SETTINGS}" "${SETTINGS}"
  fi
  if [[ ! -f "${SETTINGS}" ]]; then
    echo "Нет ${SETTINGS}"
    return 1
  fi
}

ensure_searx_env() {
  local secret
  if [[ -f "${SEARX_ENV}" ]] && grep -qE '^SEARXNG_SECRET=.' "${SEARX_ENV}" 2>/dev/null; then
    secret="$(grep -E '^SEARXNG_SECRET=' "${SEARX_ENV}" | head -1 | cut -d= -f2-)"
  else
    secret="$(openssl rand -hex 32)"
  fi

  umask 077
  cat > "${SEARX_ENV}" <<EOF
# generated by ensure-searxng.sh — https://docs.searxng.org/admin/installation-docker.html
# secret только здесь (SEARXNG_SECRET), settings.yml в git не трогаем
SEARXNG_VERSION=latest
SEARXNG_SECRET=${secret}
SEARXNG_BASE_URL=${SEARX_URL}/
SEARXNG_LIMITER=false
SEARXNG_PUBLIC_INSTANCE=false
FORCE_OWNERSHIP=true
EOF
  chmod 600 "${SEARX_ENV}"
}

ensure_app_env() {
  touch "${APP_ENV}"
  if grep -qE '^SEARXNG_URL=' "${APP_ENV}" 2>/dev/null; then
    sed -i "s|^SEARXNG_URL=.*|SEARXNG_URL=${SEARX_URL}|" "${APP_ENV}"
  else
    printf '\nSEARXNG_URL=%s\n' "${SEARX_URL}" >> "${APP_ENV}"
    touch /var/lock/xelity-restart-after-searxng
    echo ">> В .env добавлен SEARXNG_URL — нужен рестарт xelity"
  fi
}

ensure_docker
migrate_legacy_settings
ensure_searx_env
ensure_app_env
chmod -R a+rX "${CONFIG_DIR}" 2>/dev/null || true

cd "${SEARX_DIR}"
if [[ "${FORCE}" -eq 1 ]]; then
  echo ">> SearXNG: pull + recreate"
  compose pull || true
  compose up -d --remove-orphans --force-recreate
else
  echo ">> SearXNG: up -d (без pull)"
  compose up -d --remove-orphans
fi

for i in $(seq 1 15); do
  if searx_healthy; then
    echo ">> SearXNG готов (JSON): ${SEARX_URL}"
    exit 0
  fi
  echo ">> ждём SearXNG… (${i})"
  sleep 1
done

echo "!! SearXNG ещё не отдаёт JSON. Логи:"
compose ps || true
compose logs --tail=40 || true
echo "Поиск всё равно работает через DuckDuckGo/Wikipedia fallback в API."
exit 0
